# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ListOfEvents' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Moya/RxSwift', '~> 11.0'

  target 'ListOfEventsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ListOfEventsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
